MIKE/config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :services
  resources :barracks
  resources :soldiers
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MIKE/app/models/soldier.rb
class Soldier < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  belongs_to :service
  belongs_to :team
  belongs_to :barrack
  
end

MIKE/app/controllers/soldiers_controller.rb
class SoldiersController < ApplicationController
  before_action :set_soldier, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /soldiers
  # GET /soldiers.json
  def index
    @soldiers = Soldier.all
  end

  # GET /soldiers/1
  # GET /soldiers/1.json
  def show
  end

  # GET /soldiers/new
  def new
    @soldier = Soldier.new
  end

  # GET /soldiers/1/edit
  def edit
  end

  # POST /soldiers
  # POST /soldiers.json
  def create
    @soldier = Soldier.new(soldier_params)
    @soldier.user = current_user
   
  

  
    respond_to do |format|
      if @soldier.save
        format.html { redirect_to @soldier, notice: 'Soldier was successfully created.' }
        format.json { render :show, status: :created, location: @soldier }
      else
        format.html { render :new }
        format.json { render json: @soldier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /soldiers/1
  # PATCH/PUT /soldiers/1.json
  def update
    respond_to do |format|
      if @soldier.update(soldier_params)
        format.html { redirect_to @soldier, notice: 'Soldier was successfully updated.' }
        format.json { render :show, status: :ok, location: @soldier }
      else
        format.html { render :edit }
        format.json { render json: @soldier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /soldiers/1
  # DELETE /soldiers/1.json
  def destroy
    @soldier.destroy
    respond_to do |format|
      format.html { redirect_to soldiers_url, notice: 'Soldier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_soldier
      @soldier = Soldier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def soldier_params
      params.require(:soldier).permit(:i_d, :name, :grade, :user_id)
    end
end

MIKE/app/helpers/soldiers_helper.rb
module SoldiersHelper
end

MIKE/app/views/soldiers/_form.html.erb
<%= form_with(model: soldier, local: true) do |form| %>
  <% if soldier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(soldier.errors.count, "error") %> prohibited this soldier from being saved:</h2>

      <ul>
      <% soldier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :i_d %>
    <%= form.number_field :i_d %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MIKE/app/views/soldiers/edit.html.erb
<h1>Editing Soldier</h1>

<%= render 'form', soldier: @soldier %>

<%= link_to 'Show', @soldier %> |
<%= link_to 'Back', soldiers_path %>

MIKE/app/views/soldiers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Soldiers</h1>

<table>
  <thead>
    <tr>
      <th>I d</th>
      <th>Name</th>
      <th>Grade</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @soldiers.each do |soldier| %>
      <tr>
        <td><%= soldier.i_d %></td>
        <td><%= soldier.name %></td>
        <td><%= soldier.grade %></td>
        <td><%= soldier.user.email %></td>
        <td><%= link_to 'Show', soldier %></td>
        <td><%= link_to 'Edit', edit_soldier_path(soldier) %></td>
        <td><%= link_to 'Destroy', soldier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Soldier', new_soldier_path %>

MIKE/app/views/soldiers/new.html.erb
<h1>New Soldier</h1>

<%= render 'form', soldier: @soldier %>

<%= link_to 'Back', soldiers_path %>

MIKE/app/views/soldiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>I d:</strong>
  <%= @soldier.i_d %>
</p>

<p>
  <strong>Name:</strong>
  <%= @soldier.name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @soldier.grade %>
</p>

<p>
  <strong>User:</strong>
  <%= @soldier.user.email %>
</p>

<%= link_to 'Edit', edit_soldier_path(@soldier) %> |
<%= link_to 'Back', soldiers_path %>