MIKE/config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :services
  resources :barracks
  resources :soldiers
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MIKE/app/models/barrack.rb
class Barrack < ApplicationRecord
    validates :title, presence: true
    has_many :soldiers
end

MIKE/app/controllers/barracks_controller.rb
class BarracksController < ApplicationController
  before_action :set_barrack, only: [:show, :edit, :update, :destroy]

  # GET /barracks
  # GET /barracks.json
  def index
    @barracks = Barrack.all
  end

  # GET /barracks/1
  # GET /barracks/1.json
  def show
  end

  # GET /barracks/new
  def new
    @barrack = Barrack.new
  end

  # GET /barracks/1/edit
  def edit
  end

  # POST /barracks
  # POST /barracks.json
  def create
    @barrack = Barrack.new(barrack_params)

    respond_to do |format|
      if @barrack.save
        format.html { redirect_to @barrack, notice: 'Barrack was successfully created.' }
        format.json { render :show, status: :created, location: @barrack }
      else
        format.html { render :new }
        format.json { render json: @barrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barracks/1
  # PATCH/PUT /barracks/1.json
  def update
    respond_to do |format|
      if @barrack.update(barrack_params)
        format.html { redirect_to @barrack, notice: 'Barrack was successfully updated.' }
        format.json { render :show, status: :ok, location: @barrack }
      else
        format.html { render :edit }
        format.json { render json: @barrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barracks/1
  # DELETE /barracks/1.json
  def destroy
    @barrack.destroy
    respond_to do |format|
      format.html { redirect_to barracks_url, notice: 'Barrack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barrack
      @barrack = Barrack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barrack_params
      params.require(:barrack).permit(:i_d, :name_barrack, :location)
    end
end

MIKE/app/helpers/barracks_helper.rb
module BarracksHelper
end

MIKE/app/views/barracks/_form.html.erb
<%= form_with(model: barrack, local: true) do |form| %>
  <% if barrack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barrack.errors.count, "error") %> prohibited this barrack from being saved:</h2>

      <ul>
      <% barrack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :i_d %>
    <%= form.number_field :i_d %>
  </div>

  <div class="field">
    <%= form.label :name_barrack %>
    <%= form.text_field :name_barrack %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MIKE/app/views/barracks/edit.html.erb
<h1>Editing Barrack</h1>

<%= render 'form', barrack: @barrack %>

<%= link_to 'Show', @barrack %> |
<%= link_to 'Back', barracks_path %>

MIKE/app/views/barracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Barracks</h1>

<table>
  <thead>
    <tr>
      <th>I d</th>
      <th>Name barrack</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barracks.each do |barrack| %>
      <tr>
        <td><%= barrack.i_d %></td>
        <td><%= barrack.name_barrack %></td>
        <td><%= barrack.location %></td>
        <td><%= link_to 'Show', barrack %></td>
        <td><%= link_to 'Edit', edit_barrack_path(barrack) %></td>
        <td><%= link_to 'Destroy', barrack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barrack', new_barrack_path %>

MIKE/app/views/barracks/new.html.erb
<h1>New Barrack</h1>

<%= render 'form', barrack: @barrack %>

<%= link_to 'Back', barracks_path %>

MIKE/app/views/barracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>I d:</strong>
  <%= @barrack.i_d %>
</p>

<p>
  <strong>Name barrack:</strong>
  <%= @barrack.name_barrack %>
</p>

<p>
  <strong>Location:</strong>
  <%= @barrack.location %>
</p>

<%= link_to 'Edit', edit_barrack_path(@barrack) %> |
<%= link_to 'Back', barracks_path %>